### ISSUE TITLE
Missing MultiVGGFeaturesExtractor function in models/modules/losses.py

### ISSUE THREAD

**Issue by hanliyao** [itayhubara/TNRD-pytorch#1]
Dear author, i have downloaded and run your code in my local machine, however, there is missing one function in your project file. (lossses.py), can you update your ..vgg file in this project, please?
![upload file](https://user-images.githubusercontent.com/10061609/125015582-5a586b80-e0a2-11eb-8362-d4098d21943e.PNG)

**Comment by itayhubara** [comment]
I added vgg.py file. Please close the issue if it fixed the bug

**Comment by hanliyao** [comment]
thank U :)
